# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ newstructure ]
  pull_request:
    branches: [ newstructure ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install KIKIT
        run: pip3 install git+https://github.com/yaqwsx/KiKit@master
        
      - name: Install PcbDraw
        run: pip3 install PcbDraw

      - name: Install KICAD
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-5.1-releases
          sudo apt update
          sudo apt install --install-recommends kicad

      - name: Run kikit
        run: /home/runner/.local/bin/kikit fab jlcpcb --assembly --schematic ./ModuleV421/ModuleV421.sch --field LCSCStockCode --missingWarn ./ModuleV421/ModuleV421.kicad_pcb ./ModuleV421

      - name: Publish Artifacts 1
        uses: actions/upload-artifact@v2
        with:
          name: V421-Gerber
          path: |
             ./ModuleV421/bom.csv
             ./ModuleV421/pos.csv
             ./ModuleV421/gerbers.zip
          if-no-files-found: error

      - name: Run kikit for GERBER
        run: /home/runner/.local/bin/kikit fab jlcpcb --assembly --schematic ./ModuleV440/ModuleV440.sch --field LCSCStockCode --missingWarn ./ModuleV440/ModuleV440.kicad_pcb ./ModuleV440

#      - name: Run kikit for 3D print solder stencil
#        run: /home/runner/.local/bin/kikit stencil createprinted --pcbthickness 1.6 --thickness 1.0  ./ModuleV440/ModuleV440.kicad_pcb ./ModuleV440

      - name: Publish Artifacts 2
        uses: actions/upload-artifact@v2
        with:
          name: V440-Gerber
          path: |
             ./ModuleV440/bom.csv
             ./ModuleV440/pos.csv
             ./ModuleV440/gerbers.zip
          if-no-files-found: error


