name: pcb-artifacts-ControllerCurrentShuntAddOn

on:
  push:
    paths:
    - 'ControllerCurrentShuntAddOn/**.sch'
    - 'ControllerCurrentShuntAddOn/**.kicad_pcb'
    - '.github/workflows/pcb-artifacts-ControllerCurrentShuntAddOn.yaml'
  pull_request:
    paths:
    - 'ControllerCurrentShuntAddOn/**.sch'
    - 'ControllerCurrentShuntAddOn/**.kicad_pcb'
    - '.github/workflows/pcb-artifacts-ControllerCurrentShuntAddOn.yaml'
  workflow_dispatch:

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest

    steps:
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Running on branch
      run: |
        echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"
  
    - name: Update the PCBs with on default branch with git hash
      if: steps.branch-name.outputs.is_default == 'true'
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!${COMMIT}!" ControllerCurrentShuntAddOn/ControllerCurrentShuntAddOn.kicad_pcb

    - name: Update the PCBs with the git hash and BETA.
      if: steps.branch-name.outputs.is_default != 'true'
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!BETA-${COMMIT}!" ControllerCurrentShuntAddOn/ControllerCurrentShuntAddOn.kicad_pcb

    - name: Remove existing export folder
      run: |
        rm -rf ./ControllerCurrentShuntAddOn/export/

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2
      with:
        config: ./ControllerCurrentShuntAddOn/config-2layer.kibot.yaml
        dir: ./ControllerCurrentShuntAddOn/export
        schema: './ControllerCurrentShuntAddOn/ControllerCurrentShuntAddOn.sch'
        board: './ControllerCurrentShuntAddOn/ControllerCurrentShuntAddOn.kicad_pcb'

    # Splitting this out to ensure a failed kibot run will mark a check as failed.
    - name: Prepare Gerbers artifact
      run: |
        cd ControllerCurrentShuntAddOn/export/gerbers
        zip -r -j ../controllercurrentshuntaddon_gerbers.zip *        

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      if: steps.branch-name.outputs.is_default != 'true'
      with:
        name: controllercurrentshuntaddon_gerbers
        path: ControllerCurrentShuntAddOn/export/controllercurrentshuntaddon_gerbers.zip

    - name: Commit files
      if: steps.branch-name.outputs.is_default == 'true'
      run: |
        git add -f ControllerCurrentShuntAddOn/export
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git commit -m "CI: pcb-artifacts-ControllerCurrentShuntAddOn"
        git push -u origin
